/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostAnalytics = IDL.Record({
  'shares' : IDL.Nat,
  'engagementRate' : IDL.Float64,
  'likes' : IDL.Nat,
  'comments' : IDL.Nat,
  'reach' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'selectedCaption' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'idea' : IDL.Text,
  'createdAt' : IDL.Int,
  'platform' : IDL.Text,
  'analytics' : PostAnalytics,
  'optimizedCaption' : IDL.Text,
  'scheduledAt' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [Post], []),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'scheduled' : IDL.Nat,
          'published' : IDL.Nat,
          'avgEngagement' : IDL.Float64,
          'totalPosts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schedulePost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Post)], []),
  'updateAnalytics' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Opt(Post)],
      [],
    ),
  'updatePostCaption' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Post)], []),
  'updatePostHashtags' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Opt(Post)],
      [],
    ),
  'updatePostStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Post)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostAnalytics = IDL.Record({
    'shares' : IDL.Nat,
    'engagementRate' : IDL.Float64,
    'likes' : IDL.Nat,
    'comments' : IDL.Nat,
    'reach' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'selectedCaption' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'idea' : IDL.Text,
    'createdAt' : IDL.Int,
    'platform' : IDL.Text,
    'analytics' : PostAnalytics,
    'optimizedCaption' : IDL.Text,
    'scheduledAt' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [Post], []),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'scheduled' : IDL.Nat,
            'published' : IDL.Nat,
            'avgEngagement' : IDL.Float64,
            'totalPosts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schedulePost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Post)], []),
    'updateAnalytics' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Opt(Post)],
        [],
      ),
    'updatePostCaption' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Post)], []),
    'updatePostHashtags' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Opt(Post)],
        [],
      ),
    'updatePostStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Post)], []),
  });
};

export const init = ({ IDL }) => { return []; };