/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Post {
  'id' : bigint,
  'status' : string,
  'selectedCaption' : string,
  'hashtags' : Array<string>,
  'owner' : Principal,
  'idea' : string,
  'createdAt' : bigint,
  'platform' : string,
  'analytics' : PostAnalytics,
  'optimizedCaption' : string,
  'scheduledAt' : [] | [string],
}
export interface PostAnalytics {
  'shares' : bigint,
  'engagementRate' : number,
  'likes' : bigint,
  'comments' : bigint,
  'reach' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string], Post>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'scheduled' : bigint,
      'published' : bigint,
      'avgEngagement' : number,
      'totalPosts' : bigint,
    }
  >,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schedulePost' : ActorMethod<[bigint, string], [] | [Post]>,
  'updateAnalytics' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, number],
    [] | [Post]
  >,
  'updatePostCaption' : ActorMethod<[bigint, string], [] | [Post]>,
  'updatePostHashtags' : ActorMethod<[bigint, Array<string>], [] | [Post]>,
  'updatePostStatus' : ActorMethod<[bigint, string], [] | [Post]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];